DROP DATABASE IF EXISTS open_rank;
CREATE DATABASE open_rank;
USE open_rank;

CREATE TABLE Organization(
       OID INT UNSIGNED AUTO_INCREMENT NOT NULL,
       oName VARCHAR (30),
       description VARCHAR(128),
       PRIMARY KEY (OID)

) ENGINE InnoDB;


CREATE TABLE Users(
       UID INT UNSIGNED AUTO_INCREMENT NOT NULL,
       fName VARCHAR(16),
       lName VARCHAR(16),
       email VARCHAR(60),
       username VARCHAR(100),
       password VARCHAR(100),
       PRIMARY KEY (UID)
) ENGINE InnoDB;


CREATE TABLE League(
       LID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
       title VARCHAR(30),
       description VARCHAR(128),
       OID INT UNSIGNED NOT NULL,
       INDEX (OID),
       FOREIGN KEY (OID) REFERENCES Organization (OID)
       ON UPDATE CASCADE ON DELETE CASCADE,
       PRIMARY KEY (LID)

) ENGINE InnoDB;


CREATE TABLE Team(
       TID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
       title VARCHAR(30),
       rank SMALLINT UNSIGNED NOT NULL,
       LID BIGINT UNSIGNED NOT NULL,
       INDEX (LID),
       FOREIGN KEY (LID) REFERENCES League (LID)
       ON UPDATE CASCADE ON DELETE CASCADE,
       PRIMARY KEY (TID)

) ENGINE InnoDB;


CREATE TABLE Contest(
       CID BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
       title VARCHAR(30),
       LID BIGINT UNSIGNED NOT NULL,
       INDEX (LID),
       FOREIGN KEY (LID) REFERENCES League (LID)
       ON UPDATE CASCADE ON DELETE CASCADE,
       PRIMARY KEY (CID)

) ENGINE InnoDB;


CREATE TABLE Placed(
       TID BIGINT UNSIGNED NOT NULL,
       CID BIGINT UNSIGNED NOT NULL,
       placed SMALLINT,
       INDEX (TID),
       FOREIGN KEY (TID) REFERENCES Team (TID)
       ON UPDATE CASCADE ON DELETE CASCADE,
       INDEX (CID),
       FOREIGN KEY (CID) REFERENCES Contest (CID)
       ON UPDATE CASCADE ON DELETE CASCADE

) ENGINE InnoDB;
